#!/bin/bash

# The MIT License (MIT)
# Copyright (c) 2020 Siddharth S Singh
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

touch_state="$(< "$HOME/.multitouch_toggle")" # File to store the toggle state in.

# check the output of 'xinput list' for what this should be on your machine.
touch_device_name='Wacom ISDv4 E6 Finger touch'

# The app-name notify-send will use to send notifications. I use the ThinkVantage button on my X220t, hence this name.
notification_sender='ThinkVantage Button Listener'

if [[ $touch_state == "ON" ]]; then # Touch is enabled.
    touch_state="OFF" # Disable touch.
else # Touch is disabled.
    touch_state="ON" # Reenable.
fi

if [[ $touch_state == "ON" ]]; then # touch state is set to a device name.
    if [[ -n "$touch_device_name" ]]; then
       xinput set-prop "$touch_device_name" 'Device Enabled' 1 # make sure finger touch is enabled.
    fi
    # Notify user.
    notify-send -a "$notification_sender" "Touch enabled" "Finger touch has been enabled."
else # Touch state is OFF.
    if [[ -n "$touch_device_name" ]]; then # If the touchscreen is configured.
        # disable touch screen.
        xinput set-prop "$touch_device_name" 'Device Enabled' 0
        # Notify.
        notify-send -a "$notification_sender" "Touch disabled" "Finger touch has been disabled"
    fi
fi

# Save the state for next invocation.
echo "$touch_state" > "$HOME/.multitouch_toggle"
